---

- name: normalize remove skipfsck
  replace:
    dest: /boot/grub/grub.cfg
    regexp: '([\t ]+rd\.skipfsck)'
    replace: ''

- name: normalize remove fastboot
  file:
    path: /fastboot
    state: absent

- name: normalize enable fstab check
  replace:
    dest: /etc/fstab
    regexp: '(^.*)([0]+[\t ]*)$'
    replace: '\1 1'
    backup: yes

- name: normalize autorelabel
  file:
    path: /.autorelabel
    owner: root
    group: root
    state: touch

- name: normalize update grub
  command: "{{item}}"
  with_items:
    - grub2-mkconfig -o /etc/grub2.cfg

- name: normalize reboot needed
  include_tasks: reboot.yml
